id: PC2924C73
initial_creation_type: ocr
source_metadata:
  volumes:
    476990072630486b8dce40e34dbd0b5e:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: དབུ་མའི་རྒྱན་གྱི་འགྲེལ་པ།
      total_pages: 1557
      volume_number: 62
